version: "2"

run:
  timeout: 5m
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/skosovsky/prompty

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocritic
    - revive
    - testifylint
    - unconvert
    - sloglint

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
