// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const ComposedChild PromptID = "composed_child"

type ComposedChildInput struct {
	ClinicName *string `json:"clinic_name,omitempty" prompt:"clinic_name"`
}

type ComposedChildPrompt struct {
	registry prompty.Registry
}

func (p *ComposedChildPrompt) Render(ctx context.Context, input ComposedChildInput) (*prompty.RenderPlan, error) {
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	planInput, err := prompty.PlanInputFrom(input)
	if err != nil {
		return nil, fmt.Errorf("bind render input: %w", err)
	}
	plan, err := p.registry.Plan(ctx, string(ComposedChild), planInput)
	if err != nil {
		return nil, fmt.Errorf("build render plan: %w", err)
	}
	return plan, nil
}

func (p *ComposedChildPrompt) RequiredTools() []string {
	return []string{}
}

func (p *ComposedChildPrompt) ID() PromptID {
	return ComposedChild
}
