// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/skosovsky/prompty"
)

const LateBindingAgent PromptID = "late_binding_agent"

type LateBindingAgentInput struct {
	UserQuery string `json:"user_query" prompt:"user_query" validate:"required"`
}

type LateBindingAgentLateInput struct {
	PatientDossier *string `json:"patient_dossier,omitempty" prompt:"patient_dossier"`
}

type LateBindingAgentPrompt struct {
	registry prompty.PromptCatalogRegistry
}

type LateBindingAgentRecipe struct {
	inner prompty.PromptRecipe[LateBindingAgentInput, LateBindingAgentLateInput]
}

func NewLateBindingAgentRecipeFromCheckpoint(checkpoint prompty.PromptRecipeCheckpoint[LateBindingAgentInput, LateBindingAgentLateInput]) (LateBindingAgentRecipe, error) {
	if checkpoint.Descriptor.ID != string(LateBindingAgent) {
		return LateBindingAgentRecipe{}, fmt.Errorf("%s checkpoint descriptor id mismatch: %q", string(LateBindingAgent), checkpoint.Descriptor.ID)
	}
	input := checkpoint.Input
	if err := validate.Struct(&input); err != nil {
		return LateBindingAgentRecipe{}, fmt.Errorf("validate input: %w", err)
	}
	if _, err := prompty.PlanInputFrom(input); err != nil {
		return LateBindingAgentRecipe{}, fmt.Errorf("bind recipe input: %w", err)
	}
	checkpoint.Input = input
	inner, err := prompty.PromptRecipeFromCheckpoint[LateBindingAgentInput, LateBindingAgentLateInput](checkpoint)
	if err != nil {
		return LateBindingAgentRecipe{}, err
	}
	return LateBindingAgentRecipe{inner: inner}, nil
}

func (r LateBindingAgentRecipe) PromptID() PromptID {
	return LateBindingAgent
}

func (r LateBindingAgentRecipe) Checkpoint() (prompty.PromptRecipeCheckpoint[LateBindingAgentInput, LateBindingAgentLateInput], error) {
	return r.inner.Checkpoint()
}

func (r LateBindingAgentRecipe) CheckpointJSON() ([]byte, error) {
	checkpoint, err := r.Checkpoint()
	if err != nil {
		return nil, err
	}
	return json.Marshal(checkpoint)
}

func (r LateBindingAgentRecipe) Descriptor() prompty.ManifestDescriptor {
	return r.inner.Descriptor
}

func (r LateBindingAgentRecipe) BindLate(input LateBindingAgentLateInput) (LateBindingAgentRecipe, error) {
	inner, err := r.inner.BindLate(input)
	if err != nil {
		return LateBindingAgentRecipe{}, err
	}
	return LateBindingAgentRecipe{inner: inner}, nil
}

func (r LateBindingAgentRecipe) Execute(ctx context.Context, registry prompty.ManifestCheckpointRegistry) (*prompty.PromptExecution, error) {
	return r.inner.Execute(ctx, registry)
}

func (r LateBindingAgentRecipe) ExecuteWithContract(ctx context.Context, registry prompty.ManifestCheckpointRegistry, contract prompty.ToolContract) (*prompty.PromptExecution, error) {
	return r.inner.ExecuteWithContract(ctx, registry, contract)
}

func (p *LateBindingAgentPrompt) NewRecipe(ctx context.Context, input LateBindingAgentInput) (LateBindingAgentRecipe, error) {
	return p.newRecipe(ctx, input)
}

func (p *LateBindingAgentPrompt) newRecipe(ctx context.Context, input LateBindingAgentInput, options ...prompty.PromptRuntimeOptions) (LateBindingAgentRecipe, error) {
	if p.registry == nil {
		return LateBindingAgentRecipe{}, fmt.Errorf("%s recipe requires registry", string(LateBindingAgent))
	}
	if err := validate.Struct(&input); err != nil {
		return LateBindingAgentRecipe{}, fmt.Errorf("validate input: %w", err)
	}
	if _, err := prompty.PlanInputFrom(input); err != nil {
		return LateBindingAgentRecipe{}, fmt.Errorf("bind recipe input: %w", err)
	}
	desc, err := p.registry.RecommendManifestDescriptor(ctx, string(LateBindingAgent))
	if err != nil {
		return LateBindingAgentRecipe{}, fmt.Errorf("recommend manifest descriptor: %w", err)
	}
	inner, err := prompty.NewPromptRecipe[LateBindingAgentInput, LateBindingAgentLateInput](desc, input, options...)
	if err != nil {
		return LateBindingAgentRecipe{}, err
	}
	return LateBindingAgentRecipe{inner: inner}, nil
}

func (p *LateBindingAgentPrompt) RequiredTools() []string {
	return []string{}
}

func (p *LateBindingAgentPrompt) ID() PromptID {
	return LateBindingAgent
}
