// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/skosovsky/prompty"
)

const LateRequiredAgent PromptID = "late_required_agent"

type LateRequiredAgentInput struct {
	UserQuery string `json:"user_query" prompt:"user_query" validate:"required"`
}

type LateRequiredAgentLateInput struct {
	PatientDossier string `json:"patient_dossier" prompt:"patient_dossier" validate:"required"`
}

type LateRequiredAgentPrompt struct {
	registry prompty.PromptCatalogRegistry
}

type LateRequiredAgentRecipe struct {
	inner prompty.PromptRecipe[LateRequiredAgentInput, LateRequiredAgentLateInput]
}

func NewLateRequiredAgentRecipeFromCheckpoint(checkpoint prompty.PromptRecipeCheckpoint[LateRequiredAgentInput, LateRequiredAgentLateInput]) (LateRequiredAgentRecipe, error) {
	if checkpoint.Descriptor.ID != string(LateRequiredAgent) {
		return LateRequiredAgentRecipe{}, fmt.Errorf("%s checkpoint descriptor id mismatch: %q", string(LateRequiredAgent), checkpoint.Descriptor.ID)
	}
	input := checkpoint.Input
	if err := validate.Struct(&input); err != nil {
		return LateRequiredAgentRecipe{}, fmt.Errorf("validate input: %w", err)
	}
	if _, err := prompty.PlanInputFrom(input); err != nil {
		return LateRequiredAgentRecipe{}, fmt.Errorf("bind recipe input: %w", err)
	}
	checkpoint.Input = input
	inner, err := prompty.PromptRecipeFromCheckpoint[LateRequiredAgentInput, LateRequiredAgentLateInput](checkpoint)
	if err != nil {
		return LateRequiredAgentRecipe{}, err
	}
	return LateRequiredAgentRecipe{inner: inner}, nil
}

func (r LateRequiredAgentRecipe) PromptID() PromptID {
	return LateRequiredAgent
}

func (r LateRequiredAgentRecipe) Checkpoint() (prompty.PromptRecipeCheckpoint[LateRequiredAgentInput, LateRequiredAgentLateInput], error) {
	return r.inner.Checkpoint()
}

func (r LateRequiredAgentRecipe) CheckpointJSON() ([]byte, error) {
	checkpoint, err := r.Checkpoint()
	if err != nil {
		return nil, err
	}
	return json.Marshal(checkpoint)
}

func (r LateRequiredAgentRecipe) Descriptor() prompty.ManifestDescriptor {
	return r.inner.Descriptor
}

func (r LateRequiredAgentRecipe) BindLate(input LateRequiredAgentLateInput) (LateRequiredAgentRecipe, error) {
	inner, err := r.inner.BindLate(input)
	if err != nil {
		return LateRequiredAgentRecipe{}, err
	}
	return LateRequiredAgentRecipe{inner: inner}, nil
}

func (r LateRequiredAgentRecipe) Execute(ctx context.Context, registry prompty.ManifestCheckpointRegistry) (*prompty.PromptExecution, error) {
	return r.inner.Execute(ctx, registry)
}

func (r LateRequiredAgentRecipe) ExecuteWithContract(ctx context.Context, registry prompty.ManifestCheckpointRegistry, contract prompty.ToolContract) (*prompty.PromptExecution, error) {
	return r.inner.ExecuteWithContract(ctx, registry, contract)
}

func (p *LateRequiredAgentPrompt) NewRecipe(ctx context.Context, input LateRequiredAgentInput) (LateRequiredAgentRecipe, error) {
	return p.newRecipe(ctx, input)
}

func (p *LateRequiredAgentPrompt) newRecipe(ctx context.Context, input LateRequiredAgentInput, options ...prompty.PromptRuntimeOptions) (LateRequiredAgentRecipe, error) {
	if p.registry == nil {
		return LateRequiredAgentRecipe{}, fmt.Errorf("%s recipe requires registry", string(LateRequiredAgent))
	}
	if err := validate.Struct(&input); err != nil {
		return LateRequiredAgentRecipe{}, fmt.Errorf("validate input: %w", err)
	}
	if _, err := prompty.PlanInputFrom(input); err != nil {
		return LateRequiredAgentRecipe{}, fmt.Errorf("bind recipe input: %w", err)
	}
	desc, err := p.registry.RecommendManifestDescriptor(ctx, string(LateRequiredAgent))
	if err != nil {
		return LateRequiredAgentRecipe{}, fmt.Errorf("recommend manifest descriptor: %w", err)
	}
	inner, err := prompty.NewPromptRecipe[LateRequiredAgentInput, LateRequiredAgentLateInput](desc, input, options...)
	if err != nil {
		return LateRequiredAgentRecipe{}, err
	}
	return LateRequiredAgentRecipe{inner: inner}, nil
}

func (p *LateRequiredAgentPrompt) RequiredTools() []string {
	return []string{}
}

func (p *LateRequiredAgentPrompt) ID() PromptID {
	return LateRequiredAgent
}
