// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"github.com/go-playground/validator/v10"
	"github.com/skosovsky/prompty"
)

type PromptID string

var validate = validator.New()

type Prompts struct {
	SupportAgent *SupportAgentPrompt
}

func NewPrompts(r prompty.Registry) *Prompts {
	return &Prompts{SupportAgent: &SupportAgentPrompt{registry: r}}
}

func AllPromptIDs() []PromptID {
	return []PromptID{SupportAgent}
}
