// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const SupportAgent PromptID = "support_agent"

type SupportAgentInput struct {
	BotName   *string `json:"bot_name,omitempty" prompt:"bot_name"`
	UserQuery string  `json:"user_query" prompt:"user_query" validate:"required"`
}

type SupportAgentPrompt struct {
	registry prompty.Registry
}

func (p *SupportAgentPrompt) Render(ctx context.Context, input SupportAgentInput) (*prompty.RenderPlan, error) {
	if input.BotName == nil {
		v := "SupportBot"
		input.BotName = &v
	}
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	planInput, err := prompty.PlanInputFrom(input)
	if err != nil {
		return nil, fmt.Errorf("bind render input: %w", err)
	}
	plan, err := p.registry.Plan(ctx, string(SupportAgent), planInput)
	if err != nil {
		return nil, fmt.Errorf("build render plan: %w", err)
	}
	return plan, nil
}

func (p *SupportAgentPrompt) RequiredTools() []string {
	return []string{}
}

func (p *SupportAgentPrompt) ID() PromptID {
	return SupportAgent
}
