// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const ComposedConditionalMain PromptID = "composed_conditional_main"

type ComposedConditionalMainInput struct {
	ClinicName *string `json:"clinic_name,omitempty" prompt:"clinic_name"`
	Query      string  `json:"query" prompt:"query" validate:"required"`
}

type ComposedConditionalMainPrompt struct {
	registry prompty.Registry
}

func (p *ComposedConditionalMainPrompt) Render(ctx context.Context, input ComposedConditionalMainInput) (*prompty.RenderPlan, error) {
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	planInput, err := prompty.PlanInputFrom(input)
	if err != nil {
		return nil, fmt.Errorf("bind render input: %w", err)
	}
	plan, err := p.registry.Plan(ctx, string(ComposedConditionalMain), planInput)
	if err != nil {
		return nil, fmt.Errorf("build render plan: %w", err)
	}
	return plan, nil
}

func (p *ComposedConditionalMainPrompt) RequiredTools() []string {
	return []string{}
}

func (p *ComposedConditionalMainPrompt) ID() PromptID {
	return ComposedConditionalMain
}
