// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/skosovsky/prompty"
)

const ComposedChild PromptID = "composed_child"

type ComposedChildInput struct {
	ClinicName *string `json:"clinic_name,omitempty" prompt:"clinic_name"`
}

type ComposedChildPrompt struct {
	registry prompty.PromptCatalogRegistry
}

type ComposedChildRecipe struct {
	inner prompty.PromptRecipeNoLate[ComposedChildInput]
}

func NewComposedChildRecipeFromCheckpoint(checkpoint prompty.PromptRecipeNoLateCheckpoint[ComposedChildInput]) (ComposedChildRecipe, error) {
	if checkpoint.Descriptor.ID != string(ComposedChild) {
		return ComposedChildRecipe{}, fmt.Errorf("%s checkpoint descriptor id mismatch: %q", string(ComposedChild), checkpoint.Descriptor.ID)
	}
	input := checkpoint.Input
	if err := validate.Struct(&input); err != nil {
		return ComposedChildRecipe{}, fmt.Errorf("validate input: %w", err)
	}
	if _, err := prompty.PlanInputFrom(input); err != nil {
		return ComposedChildRecipe{}, fmt.Errorf("bind recipe input: %w", err)
	}
	checkpoint.Input = input
	inner, err := prompty.PromptRecipeNoLateFromCheckpoint[ComposedChildInput](checkpoint)
	if err != nil {
		return ComposedChildRecipe{}, err
	}
	return ComposedChildRecipe{inner: inner}, nil
}

func (r ComposedChildRecipe) PromptID() PromptID {
	return ComposedChild
}

func (r ComposedChildRecipe) Checkpoint() (prompty.PromptRecipeNoLateCheckpoint[ComposedChildInput], error) {
	return r.inner.Checkpoint()
}

func (r ComposedChildRecipe) CheckpointJSON() ([]byte, error) {
	checkpoint, err := r.Checkpoint()
	if err != nil {
		return nil, err
	}
	return json.Marshal(checkpoint)
}

func (r ComposedChildRecipe) Descriptor() prompty.ManifestDescriptor {
	return r.inner.Descriptor
}

func (r ComposedChildRecipe) ResponseFormat() (*prompty.SchemaDefinition, error) {
	return nil, prompty.ErrStructuredOutputUnavailable
}

func (r ComposedChildRecipe) JSONSchema() (prompty.JSONDocument, error) {
	format, err := r.ResponseFormat()
	if err != nil {
		return nil, err
	}
	return prompty.CloneJSONDocument(format.Schema), nil
}

func (r ComposedChildRecipe) Execute(ctx context.Context, registry prompty.ManifestCheckpointRegistry) (*prompty.PromptExecution, error) {
	return r.inner.Execute(ctx, registry)
}

func (r ComposedChildRecipe) ExecuteWithContract(ctx context.Context, registry prompty.ManifestCheckpointRegistry, contract prompty.ToolManifestContract) (*prompty.PromptExecution, error) {
	return r.inner.ExecuteWithContract(ctx, registry, contract)
}

func (p *ComposedChildPrompt) NewRecipe(ctx context.Context, input ComposedChildInput) (ComposedChildRecipe, error) {
	return p.newRecipe(ctx, input)
}

func (p *ComposedChildPrompt) newRecipe(ctx context.Context, input ComposedChildInput, options ...prompty.PromptRuntimeOptions) (ComposedChildRecipe, error) {
	if p.registry == nil {
		return ComposedChildRecipe{}, fmt.Errorf("%s recipe requires registry", string(ComposedChild))
	}
	if err := validate.Struct(&input); err != nil {
		return ComposedChildRecipe{}, fmt.Errorf("validate input: %w", err)
	}
	if _, err := prompty.PlanInputFrom(input); err != nil {
		return ComposedChildRecipe{}, fmt.Errorf("bind recipe input: %w", err)
	}
	desc, err := p.registry.RecommendManifestDescriptor(ctx, string(ComposedChild))
	if err != nil {
		return ComposedChildRecipe{}, fmt.Errorf("recommend manifest descriptor: %w", err)
	}
	inner, err := prompty.NewPromptRecipeNoLate[ComposedChildInput](desc, input, options...)
	if err != nil {
		return ComposedChildRecipe{}, err
	}
	return ComposedChildRecipe{inner: inner}, nil
}

func (p *ComposedChildPrompt) RequiredTools() []string {
	return []string{}
}

func (p *ComposedChildPrompt) ID() PromptID {
	return ComposedChild
}
