// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const LateRequiredAgent PromptID = "late_required_agent"

type LateRequiredAgentInput struct {
	UserQuery string `json:"user_query" prompt:"user_query" validate:"required"`
}

type LateRequiredAgentLateInput struct {
	PatientDossier string `json:"patient_dossier" prompt:"patient_dossier" validate:"required"`
}

type LateRequiredAgentPrompt struct {
	registry prompty.Registry
}

func (p *LateRequiredAgentPrompt) Render(ctx context.Context, input LateRequiredAgentInput) (*prompty.RenderPlan, error) {
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	planInput, err := prompty.PlanInputFrom(input)
	if err != nil {
		return nil, fmt.Errorf("bind render input: %w", err)
	}
	plan, err := p.registry.Plan(ctx, string(LateRequiredAgent), planInput)
	if err != nil {
		return nil, fmt.Errorf("build render plan: %w", err)
	}
	return plan, nil
}

func (p *LateRequiredAgentPrompt) WithLate(plan *prompty.RenderPlan, late LateRequiredAgentLateInput) (*prompty.RenderPlan, error) {
	if plan == nil {
		return nil, prompty.ErrNilRenderPlan
	}
	if err := validate.Struct(&late); err != nil {
		return nil, fmt.Errorf("validate late input: %w", err)
	}
	return plan.WithLateInput(late)
}

func (p *LateRequiredAgentPrompt) RequiredTools() []string {
	return []string{}
}

func (p *LateRequiredAgentPrompt) ID() PromptID {
	return LateRequiredAgent
}
