// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const LateBindingAgent PromptID = "late_binding_agent"

type LateBindingAgentInput struct {
	UserQuery string `json:"user_query" prompt:"user_query" validate:"required"`
}

type LateBindingAgentLateInput struct {
	PatientDossier *string `json:"patient_dossier,omitempty" prompt:"patient_dossier"`
}

type LateBindingAgentPrompt struct {
	registry prompty.Registry
}

func (p *LateBindingAgentPrompt) Render(ctx context.Context, input LateBindingAgentInput) (*prompty.RenderPlan, error) {
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	planInput, err := prompty.PlanInputFrom(input)
	if err != nil {
		return nil, fmt.Errorf("bind render input: %w", err)
	}
	plan, err := p.registry.Plan(ctx, string(LateBindingAgent), planInput)
	if err != nil {
		return nil, fmt.Errorf("build render plan: %w", err)
	}
	return plan, nil
}

func (p *LateBindingAgentPrompt) WithLate(plan *prompty.RenderPlan, late LateBindingAgentLateInput) (*prompty.RenderPlan, error) {
	if plan == nil {
		return nil, prompty.ErrNilRenderPlan
	}
	if err := validate.Struct(&late); err != nil {
		return nil, fmt.Errorf("validate late input: %w", err)
	}
	return plan.WithLateInput(late)
}

func (p *LateBindingAgentPrompt) RequiredTools() []string {
	return []string{}
}

func (p *LateBindingAgentPrompt) ID() PromptID {
	return LateBindingAgent
}
