// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/go-playground/validator/v10"
	"github.com/skosovsky/prompty"
)

type PromptID string

var validate = validator.New()

type PromptCatalog interface {
	RenderByID(ctx context.Context, id PromptID, input any) (*prompty.RenderPlan, error)
	Descriptor(ctx context.Context, id PromptID) (prompty.TemplateDescriptor, error)
	RenderSupportAgent(ctx context.Context, input SupportAgentInput) (*prompty.RenderPlan, error)
}

type promptCatalog struct {
	registry     prompty.Registry
	SupportAgent *SupportAgentPrompt
}

func NewPromptCatalog(r prompty.Registry) PromptCatalog {
	return &promptCatalog{registry: r, SupportAgent: &SupportAgentPrompt{registry: r}}
}

func (c *promptCatalog) RenderByID(ctx context.Context, id PromptID, input any) (*prompty.RenderPlan, error) {
	switch id {
	case SupportAgent:
		return c.SupportAgent.renderFromAny(ctx, input)
	default:
		return nil, fmt.Errorf("unknown prompt id: %q", id)
	}
}

func (c *promptCatalog) Descriptor(ctx context.Context, id PromptID) (prompty.TemplateDescriptor, error) {
	if resolver, ok := c.registry.(prompty.ManifestResolver); ok {
		return resolver.ResolveManifest(ctx, string(id))
	}
	return prompty.TemplateDescriptor{}, fmt.Errorf("prompty: registry does not implement ManifestResolver")
}

func (c *promptCatalog) RenderSupportAgent(ctx context.Context, input SupportAgentInput) (*prompty.RenderPlan, error) {
	return c.SupportAgent.Render(ctx, input)
}

func AllPromptIDs() []PromptID {
	return []PromptID{SupportAgent}
}
