// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"github.com/go-playground/validator/v10"
	"github.com/skosovsky/prompty"
)

type PromptID string

var validate = validator.New()

type PromptCatalog interface {
	Descriptor(ctx context.Context, id PromptID) (prompty.TemplateDescriptor, error)
	RenderSupportAgent(ctx context.Context, input SupportAgentInput) (*prompty.RenderPlan, error)
}

type promptCatalog struct {
	registry     prompty.DescribingRegistry
	SupportAgent *SupportAgentPrompt
}

func NewPromptCatalog(r prompty.DescribingRegistry) PromptCatalog {
	return &promptCatalog{registry: r, SupportAgent: &SupportAgentPrompt{registry: r}}
}

func (c *promptCatalog) Descriptor(ctx context.Context, id PromptID) (prompty.TemplateDescriptor, error) {
	return c.registry.DescribePrompt(ctx, string(id))
}

func (c *promptCatalog) RenderSupportAgent(ctx context.Context, input SupportAgentInput) (*prompty.RenderPlan, error) {
	return c.SupportAgent.Render(ctx, input)
}

func AllPromptIDs() []PromptID {
	return []PromptID{SupportAgent}
}
