// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const SupportAgent PromptID = "support_agent"

type SupportAgentInput struct {
	BotName   *string `json:"bot_name,omitempty" prompt:"bot_name"`
	UserQuery string  `json:"user_query" prompt:"user_query" validate:"required"`
}

func (p *Prompts) RenderSupportAgent(ctx context.Context, input SupportAgentInput) (*prompty.PromptExecution, error) {
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	tmpl, err := p.registry.GetTemplate(ctx, string(SupportAgent))
	if err != nil {
		return nil, fmt.Errorf("get template: %w", err)
	}
	vars := make(map[string]any, 2)
	if input.BotName != nil {
		vars["bot_name"] = *input.BotName
	} else {
		vars["bot_name"] = "SupportBot"
	}
	vars["user_query"] = input.UserQuery
	exec, err := tmpl.Format(ctx, vars)
	if err != nil {
		return nil, fmt.Errorf("format template: %w", err)
	}
	return exec, nil
}
