// Code generated by prompty-gen. DO NOT EDIT.

package prompts

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const SupportAgent PromptID = "support_agent"

type SupportAgentInput struct {
	BotName   *string `json:"bot_name,omitempty" prompt:"bot_name"`
	UserQuery string  `json:"user_query" prompt:"user_query" validate:"required"`
}

type SupportAgentPrompt struct {
	registry prompty.Registry
}

func (p *SupportAgentPrompt) Render(ctx context.Context, input SupportAgentInput) (*prompty.RenderPlan, error) {
	if input.BotName == nil {
		v := "SupportBot"
		input.BotName = &v
	}
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	plan, err := p.registry.Plan(ctx, string(SupportAgent), input)
	if err != nil {
		return nil, fmt.Errorf("build render plan: %w", err)
	}
	return plan, nil
}

func (p *SupportAgentPrompt) renderFromAny(ctx context.Context, input any) (*prompty.RenderPlan, error) {
	switch typed := input.(type) {
	case SupportAgentInput:
		return p.Render(ctx, typed)
	case *SupportAgentInput:
		if typed == nil {
			return nil, fmt.Errorf("invalid input type for %s: got nil pointer", SupportAgent)
		}
		return p.Render(ctx, *typed)
	default:
		var expected SupportAgentInput
		return nil, fmt.Errorf("invalid input type for %s: expected %T, got %T", SupportAgent, expected, input)
	}
}

func (p *SupportAgentPrompt) RequiredTools() []string {
	return []string{}
}

func (p *SupportAgentPrompt) ID() PromptID {
	return SupportAgent
}
